services:
 
  api:
    container_name: api
    image: evrad7/multi-server

    environment:
      PG_DATABASE: ${POSTGRES_DB}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${POSTGRES_PORT}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      
      # SECRET_KEY: ${SECRET_KEY}
      SERVER_HOST: ${SERVER_HOST}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}


    
    volumes:
      - "static_volume:/server/static"
      - "media_volume:/server/media"

  worker:
    container_name: worker
    image: evrad7/multi-worker

    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
  
  client:
    container_name: client
    image: evrad7/multi-client
    environment:
      WDS_SOCKET_PORT: 0
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: evrad7/multi-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    volumes:
      - "static_volume:/server/static"
      - "media_volume:/server/media"
 


volumes:
  static_volume:
  media_volume:

