# Generated by Django 5.1.4 on 2024-12-25 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(47)], verbose_name='index')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
